### ISSUE TITLE
commit 6064c79ab480c78a31d0ca1f368f2a0b975f9c4f breaks zammad integration as it fails for valid URL

### ISSUE THREAD

**Issue by Bosi1024** [nextcloud/integration_zammad#10]
Hi,

I am using the Zammad integration with a n FQDN like this:

`some-dashyname.domain.tld`

The **dash** in the host part of the FQDN **fails to match** the regular expression (preg_match) in the commit:

`/^(https?:\/\/)?[A-Za-z0-9]+\.[A-Za-z0-9].*/`

Some suggestions:

- It would be ideal to allow all valid FQDNs (as outlined in [rfc5890](https://tools.ietf.org/html/rfc5890#section-2.3.1) and related documents).
- Modify the regular expression to allow a more relaxed FQDN.
- Could it be achieved through [validate filters](https://www.php.net/manual/en/filter.filters.validate.php) ?

Cheers

**Comment by eneiluj** [comment]
Thanks for the bug report and sorry for the stupid bug.

Php URL check is too permissive and checking rfc5890 manually is...hard. I just want a basic check to avoid saving this URL when the setting field is filled by browser autocompletion (which can't be disabled :grin:).

I made the check more permissive and published v0.0.16. Could you confirm it works on your side?

**Comment by Bosi1024** [comment]
Hi,

thank you, I've updated and it works!
