### ISSUE TITLE
Stop polling on dashboard if the document is hidden

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/integration_zammad#14]
The integration should stop polling for notifications when the user is not watching, similar to talk:
https://github.com/nextcloud/spreed/pull/5783/

document.hidden is e.g. the case when another tab is opened in the front, which means the user does not see the updating of the content anyway?

Might apply to more integrations, I just noticed this one as I have it on my dashboard

**Comment by eneiluj** [comment]
Thanks for the suggestion. I'll also do it in all the other integration apps.
