### ISSUE TITLE
Wiki - How to

### ISSUE THREAD

**Issue by Ludovicis** [nextcloud/integration_zammad#4]
Hello,

Can you add a how to with screen capture on zammad and nextcloud, please ?

Thanks,

**Comment by eneiluj** [comment]
Which part is problematic to you?

Have you seen there are "better" explanations in v0.0.3?

Easiest setup is to create a "Personal Access Token" in Zammad and put it in your personal "Connected account" settings in Nextcloud.

**Comment by Ludovicis** [comment]
![image](https://user-images.githubusercontent.com/16205280/93937451-1d480600-fd28-11ea-9b5b-e8a628aab9d6.png)
Don't work and my oauth also.
I don't understand

**Comment by eneiluj** [comment]
Are you admin of this Zammad instance? If yes, check that "Token Access (HTTP Token Authentication)" is enabled.

**Comment by Ludovicis** [comment]
Thanks for your answer
![image](https://user-images.githubusercontent.com/16205280/93938127-17065980-fd29-11ea-82c8-f6a3d49c6fbf.png)
Same result

**Comment by eneiluj** [comment]
You made me realize the login error should be visible somewhere. Will do that soon.

In the meantime you can see the error poping in nextcloud.log when you paste the token in the settings. Could you show me what's written next to "Token Access (HTTP Token Authentication)" in nextcloud.log?

**Comment by Ludovicis** [comment]
","app":"index","method":"GET","url":"/apps/integration_zammad/notifications","message":{"Exception":"GuzzleHttp\\Exception\\RequestException","Message":"cURL error 60: SSL certificate problem: certificate has expired (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)","Code":0,"Trace":[{"file":"/var/www/html/nextcloud/3rdparty/guzzlehttp/guzzle/src/Handler/CurlFactory.php","line":155,"function":"createRejection","class":"GuzzleHttp\\Handler\\CurlFactory","type":"::"},{"file":"/var/www/html/nextcloud/3rdparty/guzzlehttp/guzzle/src/Handler/CurlFactory.php","line":105,"function":"finishError","class":"GuzzleHttp\\Handler\\CurlFactory","type":"::"},{"file":"/var/www/html/nextcloud/3rdparty/guzzlehttp/guzzle/src/Handler/CurlHandler.php","line":43,"function":"finish","class":"GuzzleHttp\\Handler\\CurlFactory","type":"::"},{"file":"/var/www/html/nextcloud/3rdparty/guzzlehttp/guzzle/src/Handler/Proxy.php","line":28,"function":"__invoke","class":"GuzzleHttp\\Handler\\CurlHandler","type":"->"},{"file":"/var/www/html/nextcloud/3rdparty/guzzlehttp/guzzle/src/Handler/Proxy.php","line":51,"function":"GuzzleHttp\\Handler\\{closure}","class":"GuzzleHttp\\Handler\\Proxy","type":"::","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/nextcloud/3rdparty/guzzlehttp/guzzle/src/PrepareBodyMiddleware.php","line":37,"function":"GuzzleHttp\\Handler\\{closure}","class":"GuzzleHttp\\Handler\\Proxy","type":"::","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/nextcloud/3rdparty/guzzlehttp/guzzle/src/Middleware.php","line":29,"function":"__invoke","class":"GuzzleHttp\\PrepareBodyMiddleware","type":"->"},{"file":"/var/www/html/nextcloud/3rdparty/guzzlehttp/guzzle/src/RedirectMiddleware.php","line":70,"function":"GuzzleHttp\\{closure}","class":"GuzzleHttp\\Middleware","type":"::","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/nextcloud/3rdparty/guzzlehttp/guzzle/src/Middleware.php","line":59,"function":"__invoke","class":"GuzzleHttp\\RedirectMiddleware","type":"->"},{"file":"/var/www/html/nextcloud/3rdparty/guzzlehttp/guzzle/src/HandlerStack.php","line":71,"function":"GuzzleHttp\\{closure}","class":"GuzzleHttp\\Middleware","type":"::","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/nextcloud/3rdparty/guzzlehttp/guzzle/src/Client.php","line":361,"function":"__invoke","class":"GuzzleHttp\\HandlerStack","type":"->"},{"file":"/var/www/html/nextcloud/3rdparty/guzzlehttp/guzzle/src/Client.php","line":163,"function":"transfer","class":"GuzzleHttp\\Client","type":"->"},{"file":"/var/www/html/nextcloud/3rdparty/guzzlehttp/guzzle/src/Client.php","line":183,"function":"requestAsync","class":"GuzzleHttp\\Client","type":"->"},{"file":"/var/www/html/nextcloud/lib/private/Http/Client/Client.php","line":233,"function":"request","class":"GuzzleHttp\\Client","type":"->"},{"file":"/var/www/html/nextcloud/apps/integration_zammad/lib/Service/ZammadAPIService.php","line":330,"function":"get","class":"OC\\Http\\Client\\Client","type":"->"},{"file":"/var/www/html/nextcloud/apps/integration_zammad/lib/Service/ZammadAPIService.php","line":127,"function":"request","class":"OCA\\Zammad\\Service\\ZammadAPIService","type":"->"},{"file":"/var/www/html/nextcloud/apps/integration_zammad/lib/Controller/ZammadAPIController.php","line":102,"function":"getNotifications","class":"OCA\\Zammad\\Service\\ZammadAPIService","type":"->"},{"file":"/var/www/html/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":169,"function":"getNotifications","class":"OCA\\Zammad\\Controller\\ZammadAPIController","type":"->"},{"file":"/var/www/html/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":100,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/html/nextcloud/lib/private/AppFramework/App.php","line":152,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/html/nextcloud/lib/private/Route/Router.php","line":308,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/var/www/html/nextcloud/lib/base.php","line":1009,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/html/nextcloud/index.php","line":37,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/www/html/nextcloud/3rdparty/guzzlehttp/guzzle/src/Handler/CurlFactory.php","Line":201,"CustomMessage":

**Comment by Ludovicis** [comment]
/apps/integration_zammad/config","message":{"Exception":"GuzzleHttp\\Exception\\RequestException","Message":"cURL error 60: SSL certificate problem: certificate has expired

**Comment by eneiluj** [comment]
Well this is the error when you display the widget and not when you set the token in the settings. But same problem I guess:

`SSL certificate problem: certificate has expired`

**Comment by Ludovicis** [comment]
Same problem, yes, my certificate has not expired...

**Comment by eneiluj** [comment]
Could you send me your Zammad instance address by email? I understand if you don't want to...

**Comment by Ludovicis** [comment]
zammad instance address send by email

**Comment by eneiluj** [comment]
Thanks for your persistence.

Ok so it means the operating system hosting your Nextcloud does not trust the certificate or gets wrong information about it.

Disabling certificate check wouldn't be a good way to solve this... Looks like we're stuck now :grin:.
