### ISSUE TITLE
Integration issue

### ISSUE THREAD

**Issue by uhuber23** [nextcloud/integration_zammad#42]
I am struggeling with the integration of zammad to our nextcloud-instance; maybe you have got an idea. 
 
I worked fine until we upgraded to nextcloud 24; after this update the connection broke and we receive no messages from the zammad instance. 
 
We have recently upgrade to 25.0.5 and tried to reintegrate the zammad-plugin, but this still failed. 
 
The only error I saw was short message: Error while saving settings: undefinded (original message is German, so this is rough translation)
 
You got an idea why this issues is coming up or where to look for further investigation?

**Comment by uhuber23** [comment]
Add-on: <html><body>


Google | Google  API ServerException\|ClientException error : Client error: `GET  https://www.googleapis.com/oauth2/v1/userinfo?alt=json` resulted in a  `401 Unauthorized` response: {   "error": {     "code": 401,     "message": "Request is missing required authentication credential.  Expected OAuth 2  (truncated...)  status code: 401 body: {   "error": {     "code": 401,     "message": "Request is missing required authentication credential.  Expected OAuth 2 access token, login cookie or other valid  authentication credential. See  https://developers.google.com/identity/sign-in/web/devconsole-project.",     "status": "UNAUTHENTICATED"   } }
-- | --



</body>
</html>

**Comment by julien-nc** [comment]
Hi, thanks for the bug report.

This is most likely not related with the google integration. Still worth checking this by testing after having disabled the google integration app.

I can't reproduce on my side. Everything works fine with integration_zammad v2.0.1 on Nextcloud v25.0.5.

I need more information:
* Nextcloud and integration_zammad versions
* When and where do you see the `Error while saving settings: undefined` message? In the admin settings? personal settings?
* How do you try to set up the authentication? OAuth or personal access tokens?
* Could you check the content of the failing request's response? Open the browser dev tools, go to the "network" tab, reproduce the bug, the request should appear in the dev tools, select it and check what's in the "response" tab.

**Comment by uhuber23** [comment]
> 

    Nextcloud and integration_zammad versions

It´s 25.0.5 and 2.0.1 

    When and where do you see the Error while saving settings: undefined message? In the admin settings? personal settings?

Personal Settings

    How do you try to set up the authentication? OAuth or personal access tokens?

Personal Access Token

    Could you check the content of the failing request's response? Open the browser dev tools, go to the "network" tab, reproduce the bug, the request should appear in the dev tools, select it and check what's in the "response" tab.

I just checked it and it still appears, even after disabling the google integration app. The debug-console (nice hint, didn´t think of it yet...) gives me:

cURL error 28: Connection timed out after 30001 milliseconds (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://zammad.heureka.co.at/api/v1/users/me"

So it looks like a network problem. We´ll take a dive into that one...


> Also, could you try setting up a test instance with Nextcloud 26? The latest integration_zammad release (v2.0.3) is for NC >= 26.

Did that (had to upgrade php first), now we are running 26.0.0 ans 2.0.3 - no change. So the problem still exists.

**Comment by marcelklehr** [comment]
Can you try fetching that URL from your nextcloud server's CLI via curl to see if you can access the remote server at all?

**Comment by marcelklehr** [comment]
Closing due to lack of response
