### ISSUE TITLE
the item activate notifications for open tickets is not saved correctly in user/connected-accounts

### ISSUE THREAD

**Issue by Ludovicis** [nextcloud/integration_zammad#5]
the item activate notifications for open tickets is not saved correctly in user/connected-accounts

{"reqId":"TTLcWinnvGkJXyyOiTly","level":3,"time":"2020-10-02T15:14:43+00:00","remoteAddr":"x","user":"x","app":"PHP","method":"PUT","url":"/apps/integration_zammad/config","message":"Undefined index: error at /var/www/html/nextcloud/apps/integration_zammad/lib/Controller/ConfigController.php#99","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36","version":"20.0.0.8"}

**Comment by eneiluj** [comment]
Ok thanks a lot for the bug report. This is the result of too much work :wink: and several little mistakes.

Could you try v0.0.5 which is released now?

**Comment by Ludovicis** [comment]
It's OK now, thanks
