### ISSUE TITLE
What is going on with the Zammad integration?

### ISSUE THREAD

**Issue by tilllt** [nextcloud/integration_zammad#9]
- the settings disappeared completely
- is this project abandoned?

i am frankly a little bit surprised by the lack of News on why there are changes to this App since it seems defunct (in purpose) right now. Anyone care to explain? We just started to use it in our team.

**Comment by eneiluj** [comment]
Hi,

> the settings disappeared completely

What do you mean? The setting fields disappeared or the values became empty?

> is this project abandoned?

No it's not. Let's find out what happens, fix the problem and I'll make a release :grin:.

> it seems defunct (in purpose)

What makes you think that? I can guarantee the last release is not meant to ship a defunct app...

**Comment by eneiluj** [comment]
The only thing that changed in latest release (v0.0.15) is that the Zammad URL is checked in various places to avoid making requests to an invalid destination URL.

Could you tell me approximately what your Zammad URL looks like? (change a few letters if you want to keep it secret)

Is there any error in the browser console log? And in nextcloud.log on the server side?
We're going to fix this error :grin:.

**Comment by tilllt** [comment]
![Screenshot_7](https://user-images.githubusercontent.com/1854364/105605202-67083200-5d96-11eb-9201-250f4311c407.jpg)
![Screenshot_8](https://user-images.githubusercontent.com/1854364/105605213-67a0c880-5d96-11eb-9333-55baabc142ef.jpg)
![Screenshot_5](https://user-images.githubusercontent.com/1854364/105605220-67a0c880-5d96-11eb-9090-87295da3ed84.jpg)
![Screenshot_6](https://user-images.githubusercontent.com/1854364/105605239-696a8c00-5d96-11eb-8688-17a358a36b92.jpg)

**Comment by tilllt** [comment]
So, as you can see: either the last NC update OR the last Zammad integration update broke something. I didnt change anything except (auto) update NC and Zammad Integration. And when i installed the Zammad Integration there was somewhere a quite detailed description on HOW to configure WHAT - for the life of me, i cant find that document again, which imho should be HERE in the readme. 

i had posted this here already, but people using the zammad intergation seem to be rare still:
https://help.nextcloud.com/t/zammad-integration-only-for-admins/104759

**Comment by tilllt** [comment]
It may very well be, that its not the Zammad Integration that is to blame here but the overall integration of NC, since the entire menu-point disappeared from the Admin settings. Its just that Zammad Integration is the only integration i have / had installed so it was kind of the first suspect.

**Comment by eneiluj** [comment]
* Could you check if there are any error in the browser console log (F12 -> "Console" tab) when you load the Dashboard page?
* I would also need the browser error log when you load the "connected accounts" admin settings as there seems to be a problem there.
* It would also be helpful if you could check the last lines of nextcloud.log when loading the Dashboard.
* Could you provide the Zammad URL you are using (or something close)?

From your screenshots, the problem can come from a bug on the server side so there is no response when the widget asks for notification OR this is simply a javascript crash and you'll see it in the browser log. In any case I need some more information.

> i had posted this here already

I'm alone working on the integration apps, I don't have enough time to check the community forum. I only answer to GitHub issues.

The integration is not only for admins. It's just about the OAuth app config. Only NC admins can set a Zammad OAuth app client/secret and then every NC user can authenticate with OAuth instead of having to generate a personal token on their own.

So even if no admin has set OAuth settings in NC, users can still use a Zammad personal token to use the integration in NC.

The instructions are in the "connected accounts" settings (admin ones and user ones).

I can't reproduce the problem on my side. I don't see why the admin settings section would disappear.

**Comment by tilllt** [comment]
Regarding the ADMIN rights i mentioned in the forum post, that obviously applies only for the DEFAULT rights an "AGENT" has, which is not enough to use the zammad integration. At least "Admin->Object" Permissions need to be additionally granted an Agent in the ROLES submenu of Zammad. Even in the disappaered documentation, i didnt see this anywhere mentioned so it was kind ob a mystery how a non admin is supposed to use it at all. 

i dont understand the scope of what possible the "Admin->Object" Permission in Zammad grants a user so it feels kind of scary just to enable without an explainer what this actually means, security wise. Of course, i can research this myself, but i think this might very well hold of a lot of people using the integration at all - and should definitely be part of the docs.

**Comment by tilllt** [comment]
```
TypeError: this.notifications.map is not a function
    items Dashboard.vue:61
    VueJS 3
    St Dashboard.vue:1
    VueJS 14
    processNotifications Dashboard.vue:158
    fetchNotifications Dashboard.vue:130
    promise callback*fetchNotifications Dashboard.vue:129
    launchLoop Dashboard.vue:119
    beforeMount Dashboard.vue:103
    VueJS 4
    <anonymous> dashboard.js:24
    rerenderPanels App.vue:263
    callbacks App.vue:199
    VueJS 10
        run
        un
        tt
        Xe
        promise callback*Ye
        tt
        update
        update
        notify
        Ce
    register App.vue:240
    register main.js:24
    <anonymous> dashboard.js:20
    EventListener.handleEvent* dashboard.js:18
    <anonymous> integration_zammad-dashboard.js:2
    <anonymous> integration_zammad-dashboard.js:2
vue.runtime.esm.js:1888:12
    VueJS 17
    processNotifications Dashboard.vue:158
    fetchNotifications Dashboard.vue:130
    (Async: promise callback)
    fetchNotifications Dashboard.vue:129
    launchLoop Dashboard.vue:119
    beforeMount Dashboard.vue:103
    VueJS 4
    <anonym> dashboard.js:24
    rerenderPanels App.vue:263
    callbacks App.vue:199
    VueJS 10
    register App.vue:240
    register main.js:24
    <anonym> dashboard.js:20
    (Async: EventListener.handleEvent)
    <anonym> dashboard.js:18
    <anonym> integration_zammad-dashboard.js:2
    <anonym> integration_zammad-dashboard.js:2

```

**Comment by tilllt** [comment]
i dont know how to properly save the Console error message to make it more meaningful for you, there doesnt seem to be a "save error" functionality so i can just Cut and Paste it here...

**Comment by tilllt** [comment]
This is in Firefox 84.0.2 (64-Bit) on WIn10

**Comment by tilllt** [comment]
this seems to be the same thing from a recent chrome:
`vue.runtime.esm.js:1888 TypeError: this.notifications.map is not a function
    at o.items (Dashboard.vue:61)
    at An.get (vue.runtime.esm.js:4479)
    at An.evaluate (vue.runtime.esm.js:4584)
    at o.items (vue.runtime.esm.js:4836)
    at o.<anonymous> (Dashboard.vue?6824:1)
    at o.e._render (vue.runtime.esm.js:3548)
    at o.r (vue.runtime.esm.js:4066)
    at An.get (vue.runtime.esm.js:4479)
    at An.run (vue.runtime.esm.js:4554)
    at pn (vue.runtime.esm.js:4310)
Qe @ vue.runtime.esm.js:1888`

**Comment by eneiluj** [comment]
It's ok, the error is explicit enough like that. Thanks.

Now I would need you to check the "Network" tab near the "Console" one. Type "zammad notifications" in the URL filter field and reload the Dashboard page. Now there should be one network request line appearing. Select it and go to the "result" tab on the right. I need the content of this tab.

Btw, the "Admin -> objects" permission is required to get the ticket state names (https://docs.zammad.org/en/latest/api/ticket-state.html?highlight=admin.object#show) which is used there https://github.com/nextcloud/integration_zammad/blob/e6e47fffa747b9bc754a80be81adad160da0b2b9/lib/Service/ZammadAPIService.php#L249 .

**Comment by tilllt** [comment]
<pre>
HTTP/1.1 302 Found
date: Sat, 23 Jan 2021 16:05:32 GMT
server: Apache/2.4.38 (Debian)
referrer-policy: no-referrer
x-content-type-options: nosniff
x-download-options: noopen
x-frame-options: SAMEORIGIN
x-permitted-cross-domain-policies: none
x-robots-tag: none
x-xss-protection: 1; mode=block
x-powered-by: PHP/7.4.14
expires: Thu, 19 Nov 1981 08:52:00 GMT
cache-control: no-store, no-cache, must-revalidate
pragma: no-cache
content-security-policy: default-src 'self'; script-src 'self' 'nonce-MXVMdWVGRlhEd2dMEtUWW01M0QxVVJ5ME1NOD06c0syV0xXZzJWMUY4Tnc1Wlc2UzRxWkJtSjJXMWJIeHBrVE9CYVZyWlU3az0='; style-src 'self' 'unsafe-inline'; frame-src *; img-src * data: blob:; font-src 'self' data:; media-src *; connect-src *; object-src 'none'; base-uri 'self';
location: https://cloud.example.de/apps/dashboard/
content-length: 0
content-type: text/html; charset=UTF-8
</pre>

**Comment by tilllt** [comment]
<pre>
GET /apps/integration_zammad/notifications HTTP/1.1
Host: cloud.example.de
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:84.0) Gecko/20100101 Firefox/84.0
Accept: application/json, text/plain, */*
Accept-Language: de,en-US;q=0.7,en;q=0.3
Accept-Encoding: gzip, deflate, br
requesttoken: EUUhTv8Gg65KJkA8Vs54I=:dwpZG8Zn2/coZRFm9hs4Y+Nutgj64QnHOrJPf4MBhPQ=
DNT: 1
Connection: keep-alive
Cookie: __Host-nc_sameSiteCookielax=true; __Host-nc_sameSiteCookiestrict=true; nc_username=user; nc_token=X5dJsmCX%2FhW8WG3mc%2Fl2; nc_session_id=60795cf38160b83795; 5266913a09457=60795cf33e5a160b83795; oc_sessionPassphrase=FfLYceRZFEmK7FwPkyAed3SK2QfwOpprWuHo8dRZViS%2FvHQXiVj9b7eQnKq1BIziIkf8gLZz6112
</pre>

dont worry, tokens are messed up with random characters

**Comment by eneiluj** [comment]
This is the "headers" tab. I need the "result" tab. I guess it's empty anyway.

**Comment by tilllt** [comment]
> 
> 
> This is the "headers" tab. I need the "result" tab. I guess it's empty anyway.

yes its empty

**Comment by eneiluj** [comment]
Could i have a screenshot with all "results" sections unfolded? I don't get why you get an error with an empty result.

Also, does it make sense that you don't get any notification? I mean, do you see notifications in Zammad interface?

**Comment by tilllt** [comment]
Zammad is working perfectly, we are using it everyday.

just to give you an idea of the "overall" error log my dashboard throws in the console, i dont know if this a "normal" amount since i rarely check the console.

<pre>
No OC found index.js:46:12
JQMIGRATE: Migrate is installed, version 1.4.1 jquery-migrate.min.js:2:551
jQuery is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. globals.js:60:15
$ is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. 5 globals.js:60:15
Notifications permissions granted App.vue:296
jQuery is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. globals.js:60:15
$ is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. globals.js:60:15
OCA.Files.Sidebar initialized Sidebar.js:37:10
Handlebars is deprecated: please ship your own, this will be removed in Nextcloud 20 globals.js:60:15
Uncaught TypeError: OCA.Files.DetailTabView is undefined
    <anonymous> https://cloud.n0ne.de/js/activity/activity-sidebar.js?v=644f5356-19:603
    <anonymous> https://cloud.n0ne.de/js/activity/activity-sidebar.js?v=644f5356-19:803
activity-sidebar.js:603:24
    <anonym> https://cloud.n0ne.de/js/activity/activity-sidebar.js?v=644f5356-19:603
    <anonym> https://cloud.n0ne.de/js/activity/activity-sidebar.js?v=644f5356-19:803
Handlebars is deprecated: please ship your own, this will be removed in Nextcloud 20 globals.js:60:15
Uncaught TypeError: n.Files.DetailTabView is undefined
    <anonymous> commentstabview.js:21
    <anonymous> commentstabview.js:756
    Webpack 3
commentstabview.js:21:23
Handlebars is deprecated: please ship your own, this will be removed in Nextcloud 20 globals.js:60:15
Uncaught TypeError: OCA.Files.DetailTabView is undefined
    <anonymous> versionstabview.js:18
    Webpack 3
versionstabview.js:18:7
OCA.Sharing.ShareSearch initialized ShareSearch.js:33:10
OCA.Sharing.ExternalLinkActions initialized ExternalLinkActions.js:33:10
OCA.Viewer initialized Viewer.js:46:10
No OCA.Files app found, viewer is now in standalone mode Viewer.vue:298
OC.getCapabilities is deprecated and will be removed in Nextcloud 21. See @nextcloud/capabilities capabilities.js:32:9
jQuery is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. 2 globals.js:60:15
Please do NOT wait for the DOMContentLoaded before registering your viewer handler Viewer.vue:217
The following mime is already registered text/csv 
Object { id: Getter & Setter, group: Getter & Setter, mimes: Getter & Setter, component: Getter & Setter, … }
Viewer.vue:511
session heartbeat polling started session-heartbeat.js:97:9
Files_PDFViewer initialized for public page 
Object { isPublicPage: null, canDownload: true, isSecureViewerAvailable: false }
public.js:30:9
Please do NOT wait for the DOMContentLoaded before registering your viewer handler Viewer.vue:217
$ is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. 5 globals.js:60:15
[DEBUG] unified-search: Unified Search initialized with the following providers 
Object { 0: {…}, 1: {…}, 2: {…}, 3: {…}, 4: {…}, 5: {…}, 6: {…}, 7: {…}, 8: {…}, 9: {…}, … }
ConsoleLogger.js:42:18
$ is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. 79 globals.js:60:15
[DEBUG] calendar: Current user principal is /remote.php/dav/principals/users/user/ 
Object { app: "calendar", uid: "user" }
ConsoleLogger.js:42:10
TypeError: this.notifications.map is not a function
    items Dashboard.vue:61
    VueJS 3
    St Dashboard.vue:1
    VueJS 7
vue.runtime.esm.js:1888:12
[INFO] calendar: 
Initial settings:
	- AppVersion: undefined
	- EventLimit: undefined
	- FirstRun: undefined
	- ShowWeekNumbers: undefined
	- ShowTasks: true
	- ShowWeekends: undefined
	- SkipPopover: undefined
	- SlotDuration: undefined
	- TalkEnabled: undefined
	- TasksEnabled: undefined
	- Timezone: Europe/Berlin
 
Object { app: "calendar", uid: "user" }
ConsoleLogger.js:46:10
[INFO] calendar: Updated moment locale: de 
Object { app: "calendar", uid: "user" }
ConsoleLogger.js:46:10
[DEBUG] calendar: The calendar app is using version 2.2019c of the timezone database 
Object { app: "calendar", uid: "user" }
ConsoleLogger.js:42:10

</pre>

**Comment by eneiluj** [comment]
I'm not suggesting your Zammad instance does not work. I'm asking if you have an empty list of notifications in Zammad? :grin:

Considering what you told me and my inspection of the code, the only thing that can happen here is that the Nextcloud controller (on the server side) gets 0 notifications when asking Zammad, then it provides an empty list to the dashboard widget but for some reason the widget does not see a list but something else, so it crashes when trying to process the list.

* First scenario: You don't have any Zammad notifications and I can fix the crash in the widget.
* Second scenario: There is a problem when getting the notifications and we need to investigate on that side too.

**Comment by tilllt** [comment]
wait one thing after the other
![Screenshot_10](https://user-images.githubusercontent.com/1854364/105607698-9de34580-5da0-11eb-869d-410ca7f762f0.jpg)

**Comment by tilllt** [comment]
i sent a testmail to our helpdesk email, as you can see i have a notification zammad but the problem stays the same in NC

![Screenshot_11](https://user-images.githubusercontent.com/1854364/105607786-3c6fa680-5da1-11eb-9d64-be55df61e8b7.jpg)
![Screenshot_12](https://user-images.githubusercontent.com/1854364/105607788-3d083d00-5da1-11eb-8197-f0ffbfb5f82c.jpg)

**Comment by eneiluj** [comment]
Thanks for your patience. Everything you say is useful.

You shouldn't get a 302 response code when asking for the notifications. This is the reason why you have an empty request.

The only reason why you could get a 302 instead of a 200 (success code) is that the app is not installed so you get redirected when asking something to the integration_zammad app that is not there. This would also explain why the admin settings section has disappeared. Could you check the app is installed?

**Comment by tilllt** [comment]
You mean the Zammad Integration App?
![Screenshot_13](https://user-images.githubusercontent.com/1854364/105608636-61194d80-5da4-11eb-8799-49e0866c6cdf.jpg)

Next Step i will deinstall & reinstall it.

**Comment by tilllt** [comment]
OK, i deactivated it. Removed it and reinstalled it ... tada! seems that has solved the problem!
Kind of the "Did You Restart the Computer" Type of solution i feel a little emberassed.

As for the other points: I understand now why the Zammad Integration needs the Admin.Object to be enabled, but looking at the API Document you sent, granting admin.object ALSO theoretically enables you to do to all other kinds of things. There probably is no way around this, but i think the docs should be upfront about the _theoretical_ security implications. 

Also there should be a little hint about adding Admin->Object to a regular Agent using the ROLES menu in Zammad.

And the last thing: i fiddled with get the OAuth Integration of Zammad and i couldnt get it to run, but maybe thats a matter for another ticket.

Thanks for your time and in general for creating the integration, it is absolutely useful for us, wgen it works ;)
Unfortunately i am really drowning in work ATM, generally i could at least contribute to the docs for your project but at this moment i cant even offer that.

**Comment by eneiluj** [comment]
Nice. I don't know what happened when you upgraded the integration app.

About the docs, I know it's bad to have barely nothing but I'm drowning in work too.

Yeah the things allowed by this Admin->Object permission should be listed in this app's doc...when there will be one.

About the OAuth settings, I'm sure you'll get it to work. The Zammad admin interface about OAuth sutff is a bit weird IMO. Just in case your problem is about getting the values: Once you've created an OAuth app in Zammad, click on the cross in the "View" column to display the client ID and secret.
![zam](https://user-images.githubusercontent.com/11291457/105609432-9b391e00-5da9-11eb-83c5-dc2a1262daf2.png)
